noinst_LTLIBRARIES = libmcterm.la

libmcterm_la_SOURCES = \
	mcterm.c mcterm.h \
	mcterm_cwd.c mcterm_cwd.h \
	mcterm_far2l.c mcterm_far2l.h \
	mcterm_filter.c mcterm_filter.h \
	mcterm_key.c mcterm_key.h \
	mcterm_proto.c mcterm_proto.h \
	mcterm_select.c mcterm_select.h \
	mcterm_setup.c mcterm_setup.h

AM_CPPFLAGS = -I$(top_srcdir) $(GLIB_CFLAGS)
